services:
  - type: web
    name: splitease-api
    env: python
    runtime: python3.11
    region: oregon
    plan: free
    rootDir: backend
    entrypoint: main:app
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:////opt/render/project/src/splitwise.db
    disk:
      name: splitease-db
      mountPath: /opt/render/project/src
      sizeGB: 1
